"""empty message

Revision ID: a92404d45082
Revises: ee9ea37b7d82
Create Date: 2026-01-13 16:52:24.727453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92404d45082'
down_revision = 'ee9ea37b7d82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_sistema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rota', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('metodo', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('ip', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_sistema', schema=None) as batch_op:
        batch_op.drop_column('ip')
        batch_op.drop_column('metodo')
        batch_op.drop_column('rota')

    # ### end Alembic commands ###
