"""estrutura inicial

Revision ID: ee9ea37b7d82
Revises: 
Create Date: 2025-12-29 22:05:24.087019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9ea37b7d82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abrigo')
    op.drop_table('chamados')
    with op.batch_alter_table('abrigos', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Ativo'::character varying"))
        batch_op.alter_column('bairro',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('cidade',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'Ativo'::character varying"))
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=2),
               existing_nullable=True,
               existing_server_default=sa.text("'Ativo'::character varying"))
        batch_op.alter_column('latitude',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Aberto'::character varying"))
        batch_op.create_foreign_key(None, 'usuarios', ['operador_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('login',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('senha',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('perfil',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('perfil',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('senha',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('login',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Aberto'::character varying"))

    with op.batch_alter_table('abrigos', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'Ativo'::character varying"))
        batch_op.alter_column('cidade',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'Ativo'::character varying"))
        batch_op.alter_column('bairro',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Ativo'::character varying"))
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               nullable=True)

    op.create_table('chamados',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('solicitante', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('abrigo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('operador_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['abrigo_id'], ['abrigos.id'], name=op.f('chamados_abrigo_id_fkey')),
    sa.ForeignKeyConstraint(['operador_id'], ['usuarios.id'], name=op.f('chamados_operador_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chamados_pkey'))
    )
    op.create_table('abrigo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('logradouro', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('bairro', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('cep', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('abrigo_pkey'))
    )
    # ### end Alembic commands ###
